# Generated by Django 5.2.1 on 2025-05-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options_client_adress_client_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
