# Generated by Django 5.2.1 on 2025-06-04 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment', models.CharField(default='', max_length=50, verbose_name='consulta')),
                ('speciliaties', models.CharField(choices=[('cardiologia', 'Cardiologia'), ('cirurgia_geral', 'Cirurgia Geral'), ('cirurgia_plastica', 'Cirurgia Plástica'), ('cirurgia_vascular', 'Cirurgia Vascular'), ('clinica_medica', 'Clínica Médica'), ('dermatologia', 'Dermatologia'), ('endocrinologia', 'Endocrinologia'), ('ginecologia_e_obstetricia', 'Ginecologia e Obstetrícia'), ('homeopatia', 'Homeopatia'), ('infectologia', 'Infectologia'), ('medicina_de_familia_e_comunidade', 'Medicina de Família e Comunidade'), ('medicina_do_trabalho', 'Medicina do Trabalho'), ('medicina_intensiva', 'Medicina Intensiva'), ('nefrologia', 'Nefrologia'), ('neurologia', 'Neurologia'), ('nutrologia', 'Nutrologia'), ('oftalmologia', 'Oftalmologia'), ('ortopedia_e_traumatologia', 'Ortopedia e Traumatologia'), ('otorrinolaringologia', 'Otorrinolaringologia'), ('pediatria', 'Pediatria'), ('pneumologia', 'Pneumologia'), ('psiquiatria', 'Psiquiatria'), ('radiologia_e_diagnostico_por_imagem', 'Radiologia e Diagnóstico por Imagem'), ('reumatologia', 'Reumatologia'), ('urologia', 'Urologia')], max_length=50, verbose_name='especialidade')),
                ('date', models.DateField(default='', verbose_name='data')),
                ('observations', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='observações')),
                ('hour', models.TimeField(default='00:00', verbose_name='horário')),
                ('available_schedule', models.BooleanField(default=False, verbose_name='horário disponível')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='data de atualização')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctors', verbose_name='médico')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='nome')),
            ],
        ),
    ]
