# Generated by Django 5.2.1 on 2025-06-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='é avaliado'),
        ),
    ]
