# Generated by Django 5.2.1 on 2025-06-02 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
        ('clients', '0003_client_photo'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('carried_out', models.BooleanField(default=False, verbose_name='realizada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em ')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='atualizado em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='cliente')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='date_schedule', to='appointment.appointment', verbose_name='data')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctors', verbose_name='médico')),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hour_schedule', to='appointment.appointment', verbose_name='horário')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agenda',
            },
        ),
    ]
