# Generated by Django 5.2.1 on 2025-05-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='carried_out',
            field=models.BooleanField(verbose_name='realizada'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data de criação'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_available',
            field=models.BooleanField(verbose_name='é avaliado'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='speciliaties',
            field=models.CharField(choices=[('cardiologia', 'Cardiologia'), ('cirurgia_geral', 'Cirurgia Geral'), ('cirurgia_plastica', 'Cirurgia Plástica'), ('cirurgia_vascular', 'Cirurgia Vascular'), ('clinica_medica', 'Clínica Médica'), ('dermatologia', 'Dermatologia'), ('endocrinologia', 'Endocrinologia'), ('ginecologia_e_obstetricia', 'Ginecologia e Obstetrícia'), ('homeopatia', 'Homeopatia'), ('infectologia', 'Infectologia'), ('medicina_de_familia_e_comunidade', 'Medicina de Família e Comunidade'), ('medicina_do_trabalho', 'Medicina do Trabalho'), ('medicina_intensiva', 'Medicina Intensiva'), ('nefrologia', 'Nefrologia'), ('neurologia', 'Neurologia'), ('nutrologia', 'Nutrologia'), ('oftalmologia', 'Oftalmologia'), ('ortopedia_e_traumatologia', 'Ortopedia e Traumatologia'), ('otorrinolaringologia', 'Otorrinolaringologia'), ('pediatria', 'Pediatria'), ('pneumologia', 'Pneumologia'), ('psiquiatria', 'Psiquiatria'), ('radiologia_e_diagnostico_por_imagem', 'Radiologia e Diagnóstico por Imagem'), ('reumatologia', 'Reumatologia'), ('urologia', 'Urologia')], max_length=50, verbose_name='especialidade'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data de atualização'),
        ),
    ]
