# Generated by Django 5.2.1 on 2025-06-01 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_client_alter_schedule_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Agenda', 'verbose_name_plural': 'Agenda'},
        ),
    ]
