# Generated by Django 5.2.1 on 2025-06-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_schedule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='available_schedule',
            field=models.BooleanField(default=False, verbose_name='horário disponível'),
        ),
    ]
