# Generated by Django 5.2.1 on 2025-05-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor',
            new_name='Doctors',
        ),
    ]
