# Generated by Django 5.2.1 on 2025-05-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_rename_doctor_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='upadated_at',
            new_name='updated_at',
        ),
    ]
